### ISSUE TITLE
The Fur Location error in UE5

### ISSUE THREAD

**Issue by StephenMhYt** [GiM-GamesInMotion/gFurPro#1]
![image](https://user-images.githubusercontent.com/26382649/218378904-a16a8d2c-9491-49bf-abf2-8f985f350e49.png)
The `Position` should not transform to world position.

**Comment by GiM-GamesInMotion** [comment]
Yeah, that doesn't look good. Unfortunately right now we don't have a programmer and I'm definitely not one.

**Comment by StephenMhYt** [comment]
float3 SkinPosition( FVertexFactoryInput Input, FVertexFactoryIntermediates Intermediates )
{
#if GPUSKIN_MORPH_BLEND
	float4 Position = float4(MorphPosition(Input, Intermediates),1);
#else
	float4 Position = float4(Intermediates.UnpackedPosition,1);
#endif

	// Note the use of mul(Matrix,Vector), bone matrices are stored transposed
	// for tighter packing.
	return mul( Intermediates.BlendMatrix, Position );
}

float4 CalcWorldPosition(FVertexFactoryInput Input, FVertexFactoryIntermediates Intermediates)
{
	float3 Position = SkinPosition(Input, Intermediates);
#if GPUSKIN_APEX_CLOTH
	if( IsSimulatedVertex(Input) )
	{
		// skinned positions
		float4 SkinnedPosition = float4(Position, 1);

		// Intermediates.SimulatedPosition is a clothing position in world coord
		float3 BlendedPos = lerp(SkinnedPosition.xyz, Intermediates.SimulatedPosition, ClothBlendWeight);
		Position = BlendedPos;
	}
#endif


#if NUM_MATERIAL_TEXCOORDS_VERTEX >= 2

	float3 FurOffset = Input.FurOffset;
	FurOffset = mul(Intermediates.BlendMatrix, float4(FurOffset.xyz, 0));

#if GFUR_PHYSICS

	float3 WorldPosition = LWCToFloat(TransformLocalToWorld(Input.Position, Intermediates.LocalToWorld));
	float FurLength = length(FurOffset);

	float3 PhysicsOffset = Input.BlendWeights.x * CalcBoneFurPhysicsOffset(Input.BlendIndices.x, WorldPosition);
	PhysicsOffset += Input.BlendWeights.y * CalcBoneFurPhysicsOffset(Input.BlendIndices.y, WorldPosition);
	PhysicsOffset += Input.BlendWeights.z * CalcBoneFurPhysicsOffset(Input.BlendIndices.z, WorldPosition);
	PhysicsOffset += Input.BlendWeights.w * CalcBoneFurPhysicsOffset(Input.BlendIndices.w, WorldPosition);
#if GPUSKIN_USE_EXTRA_INFLUENCES
	PhysicsOffset += Input.BlendWeightsExtra.x * CalcBoneFurPhysicsOffset(Input.BlendIndicesExtra.x, WorldPosition);
	PhysicsOffset += Input.BlendWeightsExtra.y * CalcBoneFurPhysicsOffset(Input.BlendIndicesExtra.y, WorldPosition);
	PhysicsOffset += Input.BlendWeightsExtra.z * CalcBoneFurPhysicsOffset(Input.BlendIndicesExtra.z, WorldPosition);
	PhysicsOffset += Input.BlendWeightsExtra.w * CalcBoneFurPhysicsOffset(Input.BlendIndicesExtra.w, WorldPosition);
#endif // GPUSKIN_USE_EXTRA_INFLUENCES

	float3 NormalVec = Intermediates.TangentToLocal[2];
	PhysicsOffset -= dot(PhysicsOffset, NormalVec) * NormalVec;
	PhysicsOffset *= pow(Input.TexCoords[1].x, FurOffsetPower);

	float PhysicOffsetLength = length(PhysicsOffset);
	float MaxPhysicsOffset = MaxPhysicsOffsetLength * FurLength;
	if (PhysicOffsetLength > MaxPhysicsOffset)
		PhysicsOffset *= MaxPhysicsOffset / PhysicOffsetLength;

	PhysicsOffset = LWCMultiplyVector(PhysicsOffset, Intermediates.WorldToLocal);
	Position += normalize(FurOffset + PhysicsOffset) * FurLength;
	
#else // GFUR_PHYSICS

	Position += FurOffset;
	
#endif // GFUR_PHYSICS

#endif

	return TransformLocalToTranslatedWorld(Position.xyz, Intermediates.LocalToWorld);
}

float4 VertexFactoryGetPreviousWorldPosition(FVertexFactoryInput Input, FVertexFactoryIntermediates Intermediates)
{
	float3 PrevSkinnedPosition = SkinPreviousPosition(Input, Intermediates);
#if GPUSKIN_APEX_CLOTH
#if GPUSKIN_APEX_CLOTH_PREVIOUS
	if (IsSimulatedVertex(Intermediates.ClothVertexInfluences[0]))
	{
		// Transform simulated position from cloth space into local space and blend with skinned position
		float4 PrevTransformedSimulatedPos = mul(float4(Intermediates.PreviousSimulatedPosition.xyz, 1), PreviousClothToLocal);
		PrevSkinnedPosition = lerp(PrevSkinnedPosition, PrevTransformedSimulatedPos.xyz, ClothBlendWeight * Intermediates.PreviousSimulatedPosition.w);
	}
#endif // GPUSKIN_APEX_CLOTH_PREVIOUS
#endif // GPUSKIN_APEX_CLOTH

	return TransformPreviousLocalPositionToTranslatedWorld(PrevSkinnedPosition, Intermediates.PrevLocalToWorld);
}

float4 VertexFactoryGetWorldPosition(FVertexFactoryInput Input, FVertexFactoryIntermediates Intermediates)
{
	return CalcWorldPosition(Input, Intermediates);
}

**Comment by StephenMhYt** [comment]
I modified the file about GFurFactory.ush, and works well.

**Comment by GiM-GamesInMotion** [comment]
Hello, any chance you could commit those changes?

**Comment by StephenMhYt** [comment]
Can you give me a role as Contributor? ortherwise, I need to create a pull request.

**Comment by StephenMhYt** [comment]
I can also commit the changes to support ue5.1

**Comment by StephenMhYt** [comment]
I create a pull request, and you can check it.
![image](https://user-images.githubusercontent.com/26382649/218971158-00444196-6394-4800-ae89-03db3521aa6a.png)

**Comment by GiM-GamesInMotion** [comment]
Hello, done. I made 5.1 the master branch.
Grateful for your contribution.
