### ISSUE TITLE
Does race conditions between game thread and render thread happen for UGFurComponent

### ISSUE THREAD

**Issue by AlexMeng1986** [GiM-GamesInMotion/gFurPro#10]
I find that some data such as ReferenceToLocal is being wroten in updatefur function of game thread, but at the same time it is being readed in updatefur_renderthread function of render thread. It seems that race condition will happen,

**Comment by GiM-GamesInMotion** [comment]
Will look into it.

**Comment by GiM-GamesInMotion** [comment]
Seems like this is intended.
