### ISSUE TITLE
Erroneous scope in UGFurComponent::UpdateFur_RenderThread()?

### ISSUE THREAD

**Issue by Christoph-M** [GiM-GamesInMotion/gFurPro#11]
https://github.com/GiM-GamesInMotion/gFurPro/blame/de2a9aee8c7edcacccefee23904d4d4d8284079c/Source/GFur/Private/FurComponent.cpp#L1113

Hey, I noticed there is this weird scope behind the if statement, is that intended? Looks like a mistake to me.

**Comment by GiM-GamesInMotion** [comment]
Thank you, will check on that.

**Comment by GiM-GamesInMotion** [comment]
fixed
