### ISSUE TITLE
[UE 5.4]Please support UE 5.4, include LWC for large world.

### ISSUE THREAD

**Issue by watsonsong** [GiM-GamesInMotion/gFurPro#18]
When upgrade to 5.4, there has some error:
The GBoneUniformStruct variable has compile error.
The GFurFactory.ush has error report about: 'cannot implicitly convert from 'FLWCMatrix' to 'FDFMatrix'

Is there any way to reslove these?

**Comment by GiM-GamesInMotion** [comment]
Hello,

I'm trying to find a programmer that would help with upgrade to 5.4.
It's getting exhausting to keep up with changes in Unreal Engine.

Tom
GiM
